services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: kemzy
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  my-app:
    build: .
    image: richman100/my-app:latest
    container_name: my-app
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://kemzy:pass123@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pgdata:
