name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: kemzy
          POSTGRES_PASSWORD: pass123
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U kemzy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Wait for PostgreSQL
        run: |
          for i in {30..0}; do
            if pg_isready -U kemzy -h localhost -p 5432; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run database migration
        env:
          DATABASE_URL: postgres://kemzy:pass123@localhost:5432/mydb
        run: npx medusa db:migrate 

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build 

      - name: login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest 